AccessTeamWeb/Areas/API/ViewModels/Modules/AddModuleVm.cs
using System.Collections.Generic;

namespace AccessTeamWeb.Areas.API.ViewModels.Modules
{
    public class AddModuleVm
    {
        public long ProductId { get; set; }
        public List<string> Modules{ get; set; }
    }
}

AccessTeamWeb/Areas/API/ViewModels/TeamMembers/AddMemberVm.cs
using System.Collections.Generic;

namespace AccessTeamWeb.Areas.API.ViewModels.TeamMembers
{
    public class AddMemberVm
    {
        public long TeamId { get; set; }
        public List<long> UserIds { get; set; }
    }
}

AccessTeamWeb/Models/ErrorViewModel.cs
namespace AccessTeamWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AccessTeamWeb/Controllers/HomeController.cs
using System.Diagnostics;
using AccessTeamWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AccessTeamWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

AccessTeamWeb/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AccessTeamWeb.Controllers.ViewModel;
using AccessTeamWeb.Manager.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using User.Dto;
using User.Services.Interface;

namespace AccessTeamWeb.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly IAuthManager _authManager;
        private readonly IToastNotification _notification;
        private readonly IUserServices _userServices;


        public LoginController(
            IUserServices userServices, IAuthManager authManager, IToastNotification notification)
        {
            _userServices = userServices;
            _authManager = authManager;
            _notification = notification;
        }


        public IActionResult Index()
        {
            try
            {
                return View(new LoginVm());
            }
            catch (Exception e)
            {
                _notification.AddErrorToastMessage(e.Message);
                return View(new LoginVm());
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVm vm)
        {
            try
            {
                var result = await _authManager.Login(vm.Email, vm.Password);
                if (result.Success) return RedirectToAction("Index", "Home");

                ModelState.AddModelError(nameof(vm.Email), result.Errors.FirstOrDefault());
                vm.Password = "";
                _notification.AddErrorToastMessage("Identity information is not matching");
                return View(vm);
            }
            catch (Exception e)
            {
                _notification.AddWarningToastMessage(e.Message);
                return View();
            }
        }

        [HttpGet]
        public IActionResult Registration()
        {
            try
            {
                return View(new UserVm());
            }
            catch (Exception ex)
            {
                _notification.AddErrorToastMessage(ex.Message);
                return View(new UserVm());
            }
        }

        [HttpPost]
        public async Task<IActionResult> Registration(UserVm vm)
        {
            try
            {
                var dto = new UserDto
                {
                    DisplayName = vm.DisplayName,
                    FirstName = vm.FirstName,
                    LastName = vm.LastName,
                    Address = vm.Address,
                    Email = vm.Email,
                    Phone = vm.Phone,
                    Password = vm.Password,
                    Gender = vm.Gender
                };
                await _userServices.CreateUser(dto);
                _notification.AddSuccessToastMessage("your first login Request has been sent to the administrator");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _notification.AddErrorToastMessage(e.Message);
                return View();
            }
        }
    }
}

AccessTeamWeb/Areas/Setup/Views/Module/AddModule.cshtml
@model AccessTeamWeb.Areas.Setup.ViewModel.ExistingModuleVm

@{
    ViewBag.Title = "Add Product";
    Layout = "_Layout";
}

<div id="module-app" class="mt-5">
    <div class="row">
        <div class="col-8">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header bg-success">
                            <h6 class="card-title mb-0">
                                <span class="fa fa-plus"></span> Add
                            </h6>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="">Name</label>
                                <input type="text" class="form-control form-control-sm" v-model="module.name" ref="moduleNameElm" v-on:keyup.enter.prevent="addModule">
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-sm btn-success mt-1 " title="Add Module" v-on:click.prevent="addModule">
                                    <li class="fa fa-plus"></li>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header bg-danger">
                            <h6 class="card-title mb-0">
                                <span class="fa fa-list"></span> Modules
                            </h6>
                        </div>
                        <div class="card-body">
                            <table class="table table-hover table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr v-for="(item, idx) in modules" :key="item.id">
                                    <td>{{idx + 1}}</td>
                                    <td>{{item.name}}</td>
                                    <td class="text-right">
                                        <button type="submit" class="btn btn-sm btn-danger" title="Remove Module" v-on:click.prevent="removeModule(item.id)">
                                            <li class="fa fa-trash"></li>
                                        </button>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <div class="card-footer">
                                <template v-if="modules.length > 0">
                                    <div class="text-right">
                                        <button class="btn btn-sm btn-success" title="Save" @@click.prevent="SaveModules" v-if="!isSaving">
                                            <span class="fa fa-check-circle"></span>
                                            Save
                                        </button>
                                        <button class="btn btn-sm btn-success" v-else>
                                            <span class="fa fa-spinner fa-spin"></span> Saving
                                        </button>
                                    </div>
                                </template>
                                <template v-else>
                                    <span class="text-muted">
                                        Add some Modules to continue
                                    </span>
                                </template>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-header bg-primary">
                    <h6 class="card-title mb-0 text-white" text-info>
                        <i class="far fa-question-circle"></i>&nbsp;Existing Module of <span class="badge bg-success">@Model.Product.Name</span>
                    </h6>
                </div>
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Modules</th>
                        <th class="text-right">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @{
                        var sn = 1;
                        foreach (var module in Model.Modules)
                        {
                            <tr>
                                <td>@(sn++)</td>
                                <th>@module.Name</th>
                                <th class="text-right">
                                    <a asp-area="Setup" asp-controller="Module" asp-action="Remove" asp-route-id="@module.Id" class="btn btn-sm btn-danger"> remove
                                    </a>
                                </th>
                            </tr>
                        }
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
    document.addEventListener('DOMContentLoaded',()=>{
       const app = Vue.createApp({
       
            data(){
                return{
                    modules : [],
                     isSaving: false,
                    module : {
                        name : ''
                    } 
                }
            },
            computed : {
                
            },
            mounted() {
                
            },
            methods : {
                addModule() {
                    if (this.module.name == "") return;
                    this.modules.push({
                       name: this.module.name,
                        id: Symbol()
                    });
                    this.module.name = "";
                    this.$refs['moduleNameElm'].focus();
                },
                removeModule(id) {
                    const userAsk = confirm("Are you Sure ?");
                    if (!userAsk)return;
                    this.modules = this.modules.filter(x => x.id != id);
                },
                async SaveModules() {
                    if (this.isSaving) return;
                    this.isSaving = true;
                    try {
                      const response = await axios.post("/API/Setup/Module/Add",{
                          productId : @Model.Product.Id,
                          modules : this.modules.map(x=>x.name)
                      });
                      alert("all Product Modules Added");
                      location.reload();
                    }catch (e){
                        alert(e.response.data.message);
                }finally {
                  this.isSaving = false;
                } 
               
            }
            },
       }); 
       const vm = app.mount("#module-app");
    });
    </script>
}

AccessTeamWeb/Areas/Setup/Views/Module/Index.cshtml
@model System.Collections.Generic.List<Settings.Entity.Module>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

AccessTeamWeb/Areas/Setup/Views/Product/Edit.cshtml
@model AccessTeamWeb.Areas.Setup.ViewModel.ProductVm

@{
    ViewBag.Title = "edit Product item";
    Layout = "_Layout";
}

<div class="card mt-5 mx-auto col-6">
    <div class="card-header bg-primary">
        <div class="card-title text-white">@Model.Name</div>
    </div>
    <form asp-area="Setup" asp-controller="Product" asp-action="Edit" method="post">
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input type="text" asp-for="Name" class="form-control form-control-sm" required>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input type="text" asp-for="Description" class="form-control form-control-sm" required>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="submit" class="btn btn-primary btn-sm mt-1" value="save">
        </div>
    </form>
</div>

AccessTeamWeb/Areas/Setup/Views/Product/Index.cshtml
@model List<Settings.Entity.Product>

@{
    ViewBag.Title = "Product List";
    Layout = "_Layout";
}
<div class="mt-4">
    <div class="mb-1 text-right">
        <a asp-area="Setup" asp-controller="Product" asp-action="New" class="btn btn-sm btn-primary"><li class="fa fa-plus"></li> New</a>
    </div>
    <div class="card">
        <div class="card-header bg-primary">
            <div class="card-title text-white mb-0">Product Setup List</div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Module Name</th>
                <th>Action</th>
                </thead>
                <tbody>
                @{
                    var sn = 1;
                    foreach (var product in Model)
                    {
                        <tr>
                            <td>@(sn++)</td>
                            <td>@product.Name</td>
                            <td>@product.Description</td>
                            <td class="text-center">
                                <a asp-area="Setup" asp-controller="Product" asp-action="Edit" asp-route-id="@product.Id" class="btn btn-success btn-sm"><li class="fa fa-edit"></li>&nbsp;Edit</a>
                                <a asp-area="Setup" asp-controller="Module" asp-action="AddModule" asp-route-id="@product.Id" class="btn btn-success btn-sm"><i class="fas fa-sitemap"></i>&nbsp;Module</a>
                                <a asp-area="Setup" asp-controller="Product" asp-action="Remove" asp-route-id="@product.Id" class="btn btn-danger btn-sm"><li class="fa fa-trash"></li>&nbsp;Remove</a>
                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

AccessTeamWeb/Areas/Setup/Views/Product/New.cshtml
@model AccessTeamWeb.Areas.Setup.ViewModel.ProductVm

@{
    ViewBag.Title = "Product Setup";
    Layout = "_Layout";
}

<div class="card mt-5 mx-auto col-6">
    <div class="card-header bg-primary">
        <div class="card-title text-white">Product Setup</div>
    </div>
    <form asp-area="Setup" asp-controller="Product" asp-action="New" method="post">
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input type="text" asp-for="Name" class="form-control form-control-sm" required>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea class="form-control form-control-sm" asp-for="Description" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="submit" class="btn btn-primary btn-sm mt-1" value="save">
        </div>
    </form>
</div>

AccessTeamWeb/Areas/Setup/Views/Survey/Edit.cshtml
@model AccessTeamWeb.Areas.Setup.ViewModel.SurveyVm

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


<div class="card col-6 mt-5 mx-auto">
    <div class="card-header bg-primary">
        <div class="card-title mb-0 text-white"><li class="fa fa-plus"></li> Add New Survey</div>
    </div>
    <form asp-area="Setup" asp-controller="Survey" asp-action="Edit" method="post">
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input type="text" asp-for="Title" class="form-control form-control-sm" required>
                <span asp-validation-for="Title" class="text-danger text-danger-sm"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea class="form-control form-control-sm" asp-for="Description" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger text-danger-sm"></span>
            </div>
            <button class="btn btn-sm btn-primary mt-2" type="submit" title="Save Survey Info"><li class="fa fa-plus"></li> Save</button>
        </div>
    </form>
</div>

AccessTeamWeb/Areas/Setup/Views/Survey/Index.cshtml
@model System.Collections.Generic.List<Settings.Entity.Survey>

@{
    ViewBag.Title = "Survey setup list";
    Layout = "_Layout";
}

<div class="mt-4">
    <div class="text-right">
        <a asp-area="Setup" asp-controller="Survey" asp-action="New" class="btn btn-sm btn-primary mb-1">
            <li class="fa fa-plus"></li>&nbsp;New
        </a>
    </div>
    <div class="card">
        <div class="card-header bg-primary">
            <div class="card-title text-white mb-0">survey setup list</div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Titile</th>
                    <th>Desctiption</th>
                    <th>RecBy</th>
                    <th>Publish Date</th>
                    <th>Due Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @{
                    var sn = 1;
                    foreach (var survey in Model)
                    {
                        <tr>
                            <td>@(sn++)</td>
                            <th>@survey.Title</th>
                            <th>@survey.Description</th>
                            <th>@survey.User.DisplayName</th>
                            <th>@survey.PublishDate</th>
                            <th>@survey.DueDate</th>
                            @if (survey.IsPublish)
                            {
                                <th class="text-center text-secondary">Published</th>
                            }
                            <th></th>
                            <th>
                                <a asp-area="Setup" asp-controller="Survey" asp-action="Edit" asp-route-id="@survey.Id" class="btn btn-sm btn-success">
                                    <li class="fa fa-pencil"></li> Edit
                                </a>
                                @if (!survey.IsPublish)
                                {
                                    <a asp-area="Setup" asp-controller="Survey" asp-action="Publish" asp-route-id="@survey.Id" class="btn btn-sm btn-info">
                                        <i class="fas fa-upload"></i> Publish
                                    </a>
                                }
                                else
                                {
                                    <a asp-area="Setup" asp-controller="Survey" asp-action="Pause" asp-route-id="@survey.Id" class="btn btn-sm btn-warning">
                                        <i class="fas fa-pause"></i> Pause
                                    </a>
                                }
                                <a asp-area="Setup" asp-controller="Survey" asp-action="Remove" asp-route-id="@survey.Id" class="btn btn-sm btn-danger">
                                    <li class="fa fa-trash"></li> Remove
                                </a>
                            </th>
                        </tr>
                    }
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

AccessTeamWeb/Areas/Setup/Views/Survey/New.cshtml
@model AccessTeamWeb.Areas.Setup.ViewModel.SurveyVm

@{
    ViewBag.Title = "Add Survey";
    Layout = "_Layout";
}

<div class="card col-6 mt-5 mx-auto">
    <div class="card-header bg-primary">
        <div class="card-title mb-0 text-white"><li class="fa fa-plus"></li> Add New Survey</div>
    </div>
    <form asp-area="Setup" asp-controller="Survey" asp-action="New" method="post">
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input type="text" asp-for="Title" class="form-control form-control-sm" required>
                <span asp-validation-for="Title" class="text-danger text-danger-sm"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea class="form-control form-control-sm" asp-for="Description" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger text-danger-sm"></span>
            </div>
            <button class="btn btn-sm btn-primary mt-2" type="submit" title="Save Survey Info"><li class="fa fa-plus"></li> Save</button>
        </div>
    </form>
</div>

AccessTeamWeb/Areas/Setup/Views/TaskSetup/Edit.cshtml
@model AccessTeamWeb.Areas.Setup.ViewModel.TaskSetupVm

@{
    ViewBag.Title = "Edit";
    Layout = "_Layout";
}

<div class="card mt-5 col-10 mx-auto">
    <div class="card-header bg-primary">
        <div class="card-title mb-0 text-white">
            Edit @Model.Type
        </div>
    </div>
    <form asp-area="Setup" asp-controller="TaskSetup" asp-action="Edit" method="post">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="Type"></label>
                        <input type="text" asp-for="Type" class="form-control form-control-sm">
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="ModuleId"></label>
                        <select asp-for="ModuleId" asp-items="Model.SelectModule()" class="form-control form-control-sm">
                            <option value="">Select</option>
                        </select>
                        <span asp-validation-for="ModuleId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="Point"></label>
                        <input type="number" min="0" max="100" asp-for="Point" class="form-control form-control-sm">
                        <span asp-validation-for="Point" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input type="text" asp-for="Description" class="form-control form-control-sm">
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <button type="submit" class="btn btn-sm btn-primary">
                        <li class="fa fa-plus"></li>&nbsp; save
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

AccessTeamWeb/Views/Login/Index.cshtml
@model AccessTeamWeb.Controllers.ViewModel.LoginVm

@{
    ViewBag.Title = "Login User";
    Layout = "_Layout";
}

<main>

    <form asp-action="Index" asp-controller="Login" method="post">
        <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background-lg="../../assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Sign in to our platform</h1>
                            </div>
                            <form asp-controller="Login" asp-action="Index" class="mt-4">
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label asp-for="Email">Your Email</label>
                                    <div class="input-group">
                                        <input type="email" class="form-control" placeholder="example@company.com" asp-for="Email" autofocus required>
                                    </div>
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label asp-for="Password">Your Password</label>
                                        <div class="input-group">
                                            <input type="password" placeholder="Password" class="form-control" asp-for="Password" required>
                                        </div>
                                    </div>
                                    <!-- End of Form -->
                                    <div class="d-flex justify-content-between align-items-top mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label mb-0" for="remember">
                                                Remember me
                                            </label>
                                        </div>
                                        <div>
                                            @* <a href="./forgot-password.html" class="small text-right">Lost password?</a> *@
                                        </div>
                                    </div>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-dark">Sign in</button>
                                </div>
                            </form>
                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    Not registered?
                                    <a asp-action="Registration" asp-controller="Login" class="fw-bold">Create account</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
</main>

AccessTeamWeb/Views/Login/Registration.cshtml
@model AccessTeamWeb.Controllers.ViewModel.UserVm

@{
    ViewBag.Title = "sign-up";
    Layout = "_Layout";
}

<div class="card card-body shadow-sm mb-4 mt-5">
    <h2 class="h5 mb-4">General information</h2>
    <form asp-action="Registration" asp-controller="Login" method="post">
        <div class="row">
            <div class="col-md-6 mb-3">
                <div>
                    <label asp-for="FirstName"></label>
                    <input class="form-control" type="text" asp-for="FirstName" placeholder="Enter your first name" required="">
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div>
                    <label asp-for="LastName"></label>
                    <input class="form-control" asp-for="LastName" type="text" placeholder="Also your last name" required="">
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-md-6 mb-3">
                <div>
                    <label asp-for="DisplayName"></label>
                    <input class="form-control" asp-for="DisplayName" type="text" placeholder="Display Name" required="">
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label asp-for="Gender">Gender</label>
                <select class="form-select mb-0" asp-for="Gender">
                    <option selected="selected">select</option>
                    <option value="Female">Female</option>
                    <option value="Male">Male</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input class="form-control" asp-for="Address" placeholder="Kathmandu - Nepal" required="">
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="form-group">
                    <label asp-for="Phone">Phone</label>
                    <input class="form-control" asp-for="Phone" type="text" placeholder="+12-345 678 910" required="">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <div class="form-group">
                    <label asp-for="Email">Email</label>
                    <input class="form-control" asp-for="Email" type="email" placeholder="name@company.com" required="">
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input class="form-control" asp-for="Password" type="password" placeholder="@@#989584958" required="">
                </div>
            </div>
        </div>
        <div class="mt-3">
            <input type="submit" class="btn btn-black" value="Request for Registration">
        </div>
    </form>
</div>